In [6]:
import tensorflow as tf

In [7]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
cifar = tf.keras.datasets.cifar100
(x_train, y_train), (x_test, y_test) = cifar.load_data()

169001437/169001437 [==============================] - 16s 0us/step


In [8]:
model = tf.keras.applications.ResNet50(
    include_top=True,
    weights=None,
    input_shape=(32, 32, 3),
    classes=100,)

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer="adam", loss=loss_fn, metrics=["accuracy"])

In [ ]:
model.fit(x_train, y_train, epochs=5, batch_size=64)

Epoch 1/5


2023-05-17 01:53:16.282687: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


782/782 [==============================] - 67s 81ms/step - loss: 4.7888 - accuracy: 0.0705
Epoch 2/5
386/782 [=============>................] - ETA: 30s - loss: 4.4224 - accuracy: 0.0980

In [7]:
import numpy as np
x= np.random.random((10,2))
x

array([[0.46683661, 0.80398027],
       [0.33444472, 0.25772158],
       [0.29179678, 0.57681817],
       [0.29429115, 0.18391033],
       [0.27938592, 0.96661556],
       [0.91828227, 0.2430433 ],
       [0.75951748, 0.60578919],
       [0.36460157, 0.37380373],
       [0.64500227, 0.35875453],
       [0.07751354, 0.08266184]])

In [8]:
x[:,-1]

array([0.80398027, 0.25772158, 0.57681817, 0.18391033, 0.96661556,
       0.2430433 , 0.60578919, 0.37380373, 0.35875453, 0.08266184])

In [1]:
range(1,6)

range(1, 6)

In [2]:
list(range(1,6
          ))

[1, 2, 3, 4, 5]

In [3]:
biu = [1,2,3,4]

In [4]:
biu


[1, 2, 3, 4]

In [6]:
[[1,2,3],[2,3,4]]

[[1, 2, 3], [2, 3, 4]]

In [7]:
[[[1,2,3],[2,3,4]],
[[3,4,5],[4,5,6]]]

[[[1, 2, 3], [2, 3, 4]], [[3, 4, 5], [4, 5, 6]]]

In [8]:
biu2= [[[1,2,3],[2,3,4]],
[[3,4,5],[4,5,6]]]


In [9]:
biu2[1]

[[3, 4, 5], [4, 5, 6]]

In [11]:
biu2[0]

[[1, 2, 3], [2, 3, 4]]

In [16]:
biu2[0][0][0]

1

In [24]:
import numpy as np
x= np.random.random((32,10))
y= np.random.random((10,))

In [25]:
y

array([0.70990952, 0.27270115, 0.79043622, 0.27613101, 0.97769732,
       0.58957234, 0.32911854, 0.2865084 , 0.29064326, 0.35392086])

In [28]:
y= np.expand_dims(y, axis= 0)

In [29]:
y

array([[0.70990952, 0.27270115, 0.79043622, 0.27613101, 0.97769732,
        0.58957234, 0.32911854, 0.2865084 , 0.29064326, 0.35392086]])

In [30]:
[y]

[array([[0.70990952, 0.27270115, 0.79043622, 0.27613101, 0.97769732,
         0.58957234, 0.32911854, 0.2865084 , 0.29064326, 0.35392086]])]

In [31]:
[y]*32

[array([[0.70990952, 0.27270115, 0.79043622, 0.27613101, 0.97769732,
         0.58957234, 0.32911854, 0.2865084 , 0.29064326, 0.35392086]]),
 array([[0.70990952, 0.27270115, 0.79043622, 0.27613101, 0.97769732,
         0.58957234, 0.32911854, 0.2865084 , 0.29064326, 0.35392086]]),
 array([[0.70990952, 0.27270115, 0.79043622, 0.27613101, 0.97769732,
         0.58957234, 0.32911854, 0.2865084 , 0.29064326, 0.35392086]]),
 array([[0.70990952, 0.27270115, 0.79043622, 0.27613101, 0.97769732,
         0.58957234, 0.32911854, 0.2865084 , 0.29064326, 0.35392086]]),
 array([[0.70990952, 0.27270115, 0.79043622, 0.27613101, 0.97769732,
         0.58957234, 0.32911854, 0.2865084 , 0.29064326, 0.35392086]]),
 array([[0.70990952, 0.27270115, 0.79043622, 0.27613101, 0.97769732,
         0.58957234, 0.32911854, 0.2865084 , 0.29064326, 0.35392086]]),
 array([[0.70990952, 0.27270115, 0.79043622, 0.27613101, 0.97769732,
         0.58957234, 0.32911854, 0.2865084 , 0.29064326, 0.35392086]]),
 array([[0.70

In [33]:
list(enumerate(["a","b","c"]))

[(0, 'a'), (1, 'b'), (2, 'c')]

In [34]:
range(1,6)

range(1, 6)

In [3]:
import numpy as np
from scipy import stats
import random 
np.random.rand(5,5)

array([[0.96176125, 0.81711456, 0.24286294, 0.72811232, 0.06233572],
       [0.23578879, 0.35645286, 0.44039592, 0.38768202, 0.04925443],
       [0.79448752, 0.33965918, 0.86603321, 0.75560912, 0.52723588],
       [0.83715738, 0.58707063, 0.87553573, 0.51678569, 0.05730022],
       [0.58611308, 0.04985855, 0.71669818, 0.06263374, 0.89046098]])

In [4]:
np.random.randint(0,5)

3

In [8]:
pow(0.99,50)

0.6050060671375364

In [11]:
np.zeros((3,))

array([0., 0., 0.])

In [15]:
np.zeros(3)

array([0., 0., 0.])